# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ansih/kantox-poc
  pullPolicy: IfNotPresent
  tag: ansih/kantox-poc:v1.9.0

#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

service:
  name: hello-world
  type: LoadBalancer
  externalPort: 8000
  internalPort: 8000

