---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ansih/kantox-poc:v1.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
