name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_REPO: ansih/kantox-poc
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: get tag value
      id: taggerdyrun
      uses: anothrNick/github-tag-action@1.67.0
      env:
        WITH_V: true
        DRY_RUN: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./hello-world
        push: true
        tags: ${{ env.IMAGE_REPO }}:${{ steps.taggerdyrun.outputs.new_tag }}
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Update helm values and charts
      id: update
      run: |
        pwd
        sed -i 's+tag:.*+tag: "${{ steps.taggerdyrun.outputs.new_tag }}"+g' charts/values.yaml
        version=$(echo "${{steps.taggerdyrun.outputs.new_tag}}" | tr -d "v")
        echo "version=$version" >> "$GITHUB_OUTPUT"
        git add .
        git diff
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push
      env:
        RUN_NUMBER: ${{ github.run_number }}
    - name: Update tag in git
      id: tagger
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
    - name: Install Helm
      uses: azure/setup-helm@v3
    - name: Publish helm chart
      run: |
        git checkout gh-pages
        git merge main --allow-unrelated-histories
        helm package charts --version ${{ steps.update.outputs.version }} --app-version ${{ steps.taggerdyrun.outputs.new_tag }} -d docs
        helm repo index docs/ --url https://anishvm.github.io/kantox-poc-02/
        cat docs/index.yaml
        git commit -a -m "updated index.yaml"
        git push --set-upstream origin gh-pages