name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ansih/kantox-poc
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./hello-world
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: modify the image
      run: |
        git config --global user.email "anishvm@users.noreply.github.com"
        git config --global user.name "anishvm"
        cd hello-world
        cat deployment.yml
        pwd
        sed -i "s+ansih/kantox-poc.*+ansih/kantox-poc:${{ steps.meta.outputs.tags }}+g" deployment.yml
        cat deployment.yml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push
      env:
        RUN_NUMBER: ${{ github.run_number }}