name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_REPO: ansih/kantox-poc
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.taggerdyrun.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: get tag value
      id: taggerdyrun
      uses: anothrNick/github-tag-action@1.36.0
      env:
        WITH_V: true
        DRY_RUN: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./hello-world
        push: true
        tags: ${{ env.IMAGE_REPO }}:${{ steps.taggerdyrun.outputs.new_tag }}
#    - name: Update image tag in k8s manifest
#      run: |
#        git config --global user.email "anishvm@users.noreply.github.com"
#        git config --global user.name "anishvm"
#        pwd
#        sed -i "s+image:.*+image: ${{ env.IMAGE_REPO }}:${{ steps.taggerdyrun.outputs.new_tag }}+g" hello-world/deployment.yml
#        cat hello-world/deployment.yml
#        git add .
#        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
#        git push
#      env:
##        RUN_NUMBER: ${{ github.run_number }}
#    - name: Update tag in git
#      id: tagger
#      uses: anothrNick/github-tag-action@1.36.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.PAT }}
#        WITH_V: true


  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Update helm values and charts
        run: |
          pwd
          sed -i 's+tag:.*+tag: "${{ needs.build.outputs.tag }}"+g' charts/values.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push
        env:
          RUN_NUMBER: ${{ github.run_number }}
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Publish helm chart
        env:
          VERSION: ${{ needs.build.outputs.tag }}//v
        run: |
          helm package charts --version ${{ github.run_number }} --app-version ${{ github.run_number }} -d docs
