name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: test
      env:
        REPO_NAME: $GITHUB_ACTION_REPOSITORY
      run: |
        echo $REPO_NAME
    - name: version for each merge
      id: tagger
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./hello-world
        push: true
        tags: $GITHUB_ACTION_REPOSITORY:${{ steps.tagger.outputs.new_tag }}
    - name: Update image tag in k8s manifest
      run: |
        git config --global user.email "anishvm@users.noreply.github.com"
        git config --global user.name "anishvm"
        pwd
        sed -i "s+image:.*+image: ${{ steps.tagger.outputs.new_tag }}+g" hello-world/deployment.yml
        cat hello-world/deployment.yml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push
      env:
        RUN_NUMBER: ${{ github.run_number }}