name: Prod-Deployment
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_REPO: ansih/kantox-poc
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: get tag value
      id: taggerdyrun
      uses: anothrNick/github-tag-action@1.67.0
      env:
        WITH_V: true
        DRY_RUN: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./hello-world
        push: true
        tags: ${{ env.IMAGE_REPO }}:${{ steps.taggerdyrun.outputs.new_tag }}
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Update tag in git
      id: tagger
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
    - name: Install Helm
      uses: azure/setup-helm@v3
    - name: Publish helm chart
      run: |
        git checkout gh-pages
        version=$(echo "${{steps.taggerdyrun.outputs.new_tag}}" | tr -d "v")
        sed -i 's+tag:.*+tag: "${{ steps.taggerdyrun.outputs.new_tag }}"+g' charts/values.yaml
        helm package charts --version $version --app-version ${{ steps.taggerdyrun.outputs.new_tag }} -d docs     
        helm repo index docs/ --url https://anishvm.github.io/kantox-poc-02/
        cat docs/index.yaml
        git add -A
        git commit -m "updated index.yaml for version $version"
        git push